name: Checkout Code

description: checkout code

inputs:
  machine:
    description: If set to other value, the job need ssh
    required: false
    default: 'local'
#  working_path:
#    description: ci work home
#    required: true
#    default: ''

runs:
  using: composite
  steps:
    - name : checkout
      env:
        MACHINE: ${{ inputs.machine }}
      shell: bash
      run: |
        function checkout_code(){
          echo """
          mkdir -p "${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}" && cd "${DEEPLINK_PATH}/${GITHUB_RUN_NUMBER}" && rm -rf source
          if [ -n "${{ github.event.pull_request.head.repo.full_name }}" ] && [[ ! "${{ github.event.pull_request.head.repo.full_name }}" == *DeepLink-org* ]]; then
            git clone ${{ github.event.pull_request.head.repo.ssh_url }} source
            cd source && git checkout ${{ github.event.pull_request.head.sha }}
            git remote add mainrepo git@github.com:"${GITHUB_REPOSITORY}".git
            git fetch  mainrepo && git merge --no-edit mainrepo/${{ github.base_ref }}
          else
            git clone ${{ github.event.repository.ssh_url }} source && cd source
            if [ "${GITHUB_EVENT_NAME}" == "pull_request" ]; then
              git checkout ${{ github.event.pull_request.head.sha }} && git merge --no-edit ${{ github.base_ref }}
            else
              git checkout ${{ github.sha }}
            fi
          fi
          git submodule update --init --recursive """
        }
        echo "${GITHUB_RUN_ID}" "${RUNNER_NAME}"
        echo ${DEEPLINK_PATH}
        env
        if [ ${MACHINE} != "local" ];then
          ssh ${MACHINE}  "$(typeset -f checkout_code); checkout_code "
        else

          checkout_code
        fi
